version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing build dependencies..."
      - python -m pip install --upgrade pip
      - python -m pip install pipenv
      - echo "Installing project dependencies with pipenv..."
      - cd agentaicli
      - pipenv install --dev
  pre_build:
    commands:
      - echo "Running tests..."
      - pipenv run python -m pytest
  build:
    commands:
      - echo "Packaging the Lambda function..."
      - zip -r ../agentai-cli-lambda.zip .
      - cd ..
  post_build:
    commands:
      - echo "Uploading Lambda package to S3 with versioning..."
      - VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - LAMBDA_KEY=lambda/agentai-cli-lambda-$VERSION.zip
      - aws s3 cp agentai-cli-lambda.zip s3://$CODE_BUCKET/$LAMBDA_KEY
      - aws ssm put-parameter --name /agentai-cli/lambda/version --value $VERSION --type String --overwrite
      - echo "Preparing CloudFormation parameters..."
      - echo "{\"LambdaCodeBucket\":\"$CODE_BUCKET\",\"LambdaCodeKey\":\"$LAMBDA_KEY\",\"IamStackName\":\"agentaicli-iam\"}" > parameters.json
artifacts:
  files:
    - agentai-cli-lambda.zip
    - cloudformation/AgentAiCliLambda.yml
    - parameters.json 