version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies with pipenv..."
      - pipenv install
  build:
    commands:
      - echo "Packaging the Lambda function..."
      - cd agentaicli
      - zip -r ../agentai-cli-lambda.zip .
  post_build:
    commands:
      - echo "Uploading Lambda package to S3 with versioning..."
      - VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws s3 cp ../agentai-cli-lambda.zip s3://$CODE_BUCKET/lambda/agentai-cli-lambda-$VERSION.zip
      - aws ssm put-parameter --name /agentai-cli/lambda/version --value $VERSION --type String --overwrite
artifacts:
  files:
    - agentai-cli-lambda.zip 